# Generated by Django 3.2.12 on 2022-03-01 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_searchquery_last_fetched_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchquery',
            options={'verbose_name': 'Search Query', 'verbose_name_plural': 'Search Queries'},
        ),
        migrations.AlterModelOptions(
            name='videoresult',
            options={'verbose_name': 'Video Result', 'verbose_name_plural': 'Video Results'},
        ),
    ]
