# Generated by Django 3.2.12 on 2022-03-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20220301_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('is_exhausted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'YouTube Key',
                'verbose_name_plural': 'YouTube Keys',
            },
        ),
    ]
